import { Trip, CommunityReview, HiddenGem, SafetyZone, UserProfile } from "@/types";
import { generateAiTrip } from "./ai-engine";

export const INITIAL_USER: UserProfile = {
  id: "usr-yatrik-001",
  name: "Ananya Sharma",
  email: "ananya.yatri@yatrik.ai",
  avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=250&q=80",
  coins: 1450,
  level: 4,
  rankTitle: "Top Explorer",
  tripsCompleted: 12,
  countriesVisited: 5,
  citiesVisited: 18,
  distanceKm: 14200,
  badges: [
    { name: "Safety Pioneer", icon: "ShieldCheck", description: "Contributed 10+ verified safety reviews for women solo travelers", unlockedAt: "2026-05-12" },
    { name: "Gem Hunter", icon: "Sparkles", description: "Discovered 5 secret uncrowded local spots", unlockedAt: "2026-06-01" },
    { name: "Budget Wizard", icon: "Wallet", description: "Planned 3 trips under target budget with 100% accuracy", unlockedAt: "2026-07-15" },
    { name: "Community Hero", icon: "Award", description: "Upvoted by over 500 travelers for authentic scam alerts", unlockedAt: "2026-07-22" },
  ],
  wishlist: ["Kyoto, Japan", "Santorini, Greece", "Leh Ladakh, India", "Banff, Canada"],
};

export const DEFAULT_TRIPS: Trip[] = [
  generateAiTrip({
    destination: "Goa",
    budget: 25000,
    days: 4,
    travelers: 1,
    travelerType: "Women Solo",
    transportMode: "Flight",
    preferences: ["Hidden Gems", "Food & Cafes", "Photography", "Nightlife"],
  }),
  generateAiTrip({
    destination: "Tokyo",
    budget: 120000,
    days: 6,
    travelers: 2,
    travelerType: "Couple",
    transportMode: "Flight",
    preferences: ["Luxury", "Food & Cafes", "Cultural & Heritage"],
  }),
];

export const INITIAL_REVIEWS: CommunityReview[] = [
  {
    id: "rev-1",
    userName: "Priya V.",
    userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    userBadge: "Trusted Traveller",
    destination: "Goa, India",
    placeName: "Fontainhas Latin Quarter Cafe",
    category: "Hidden Gem",
    rating: 4.9,
    safetyScore: 98,
    comment: "Super safe for women solo travelers even around 9 PM. Street lights are super bright, locals are warm and friendly, and coffee cost only ₹180!",
    photos: [
      "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=600&q=80"
    ],
    actualExpense: 350,
    upvotes: 84,
    coinsEarned: 100,
    createdAt: "2 hours ago",
  },
  {
    id: "rev-2",
    userName: "Rohan Malhotra",
    userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    userBadge: "Top Explorer",
    destination: "Manali, Himachal",
    placeName: "Old Manali Taxi Counter Scam",
    category: "Scam Alert",
    rating: 2.1,
    safetyScore: 70,
    comment: "Beware! Unofficial agents charge ₹2500 for Solang Valley. Always use the government prepay counter right next to Mall Road (costs only ₹1100).",
    scamWarning: "Overcharging taxicab counter without meter.",
    photos: [],
    actualExpense: 1100,
    upvotes: 142,
    coinsEarned: 150,
    createdAt: "Yesterday",
  },
  {
    id: "rev-3",
    userName: "Sneha Reddy",
    userAvatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80",
    userBadge: "Community Hero",
    destination: "Udaipur, Rajasthan",
    placeName: "Lake Pichola Sunset Viewpoint",
    category: "Safety Tip",
    rating: 5.0,
    safetyScore: 96,
    comment: "High female solo safety score! 24/7 tourist police guards present near Ambrai Ghat. Super romantic and peaceful sunset view.",
    photos: [
      "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=600&q=80"
    ],
    actualExpense: 0,
    upvotes: 95,
    coinsEarned: 120,
    createdAt: "3 days ago",
  }
];

export const INITIAL_GEMS: HiddenGem[] = [
  {
    id: "gem-1",
    title: "Butterfly Beach Secret Cove",
    destination: "South Goa",
    category: "Secret Beach",
    description: "Accessible via a short 15-min forest hike or boat ride. Pristine turquoise waters, zero crowd, dolphins spotted during early morning.",
    lat: 15.0125,
    lng: 73.9871,
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80",
    rating: 4.9,
    crowdLevel: "Low",
    bestTime: "6:30 AM - 9:00 AM",
    isWomenSafe: true,
  },
  {
    id: "gem-2",
    title: "Sethi Cafe & Rooftop Library",
    destination: "Old Manali",
    category: "Secret Cafe",
    description: "Nestled away from main market noise. Serves organic mountain herbal teas, woodfired pizzas, and offers panoramic view of snowy peaks.",
    lat: 32.2496,
    lng: 77.1892,
    image: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=600&q=80",
    rating: 4.8,
    crowdLevel: "Low",
    bestTime: "4:00 PM - 7:30 PM",
    isWomenSafe: true,
  },
  {
    id: "gem-3",
    title: "Baga Creek Sunrise Point",
    destination: "North Goa",
    category: "Sunrise Point",
    description: "Far away from noisy night clubs. Calm water mirror reflections, ideal for golden hour photography and yoga.",
    lat: 15.5562,
    lng: 73.7516,
    image: "https://images.unsplash.com/photo-1470240731273-7821a6eeb6bd?auto=format&fit=crop&w=600&q=80",
    rating: 4.9,
    crowdLevel: "Low",
    bestTime: "6:00 AM - 7:15 AM",
    isWomenSafe: true,
  }
];

export const SAFETY_ZONES: SafetyZone[] = [
  {
    id: "sz-1",
    name: "Panaji Central Heritage Corridor",
    city: "Goa",
    safetyScore: 97,
    lightingScore: 9,
    crowdDensity: "High",
    hasPolicePatrol: true,
    hasHospitalNearby: true,
    verifiedSafeHotels: ["Vivanta Goa", "Postcard Velha", "Heritage Inn"],
    verifiedSafeCafes: ["Cafe Bodega", "Bombay Coffee Roasters", "Verandah"],
    description: "Extremely well-lit tourist streets, continuous pink police patrol, high community safety rating.",
    lat: 15.4989,
    lng: 73.8278,
  },
  {
    id: "sz-2",
    name: "Old Manali Village Promenade",
    city: "Manali",
    safetyScore: 92,
    lightingScore: 8,
    crowdDensity: "Moderate",
    hasPolicePatrol: true,
    hasHospitalNearby: true,
    verifiedSafeHotels: ["Zostel Old Manali", "ManuAllaya Resort"],
    verifiedSafeCafes: ["Dylan's Toasted & Roasted", "Cafe 1947"],
    description: "Pedestrian-friendly café area with friendly local shopkeepers and clear CCTV coverage.",
    lat: 32.2496,
    lng: 77.1892,
  },
  {
    id: "sz-3",
    name: "Shibuya & Harajuku Safe Transit Corridor",
    city: "Tokyo",
    safetyScore: 99,
    lightingScore: 10,
    crowdDensity: "High",
    hasPolicePatrol: true,
    hasHospitalNearby: true,
    verifiedSafeHotels: ["Shibuya Stream Excel Hotel", "TRUNK Hotel"],
    verifiedSafeCafes: ["About Life Coffee Brewers", "Fuglen Tokyo"],
    description: "Globally top-ranked safety rating with 24-hour convenience stores and emergency help boxes every 200m.",
    lat: 35.6580,
    lng: 139.7016,
  }
];
